### ISSUE TITLE
Orama Cloud: error with web import

### ISSUE THREAD

**Issue by djibe** [askorama/oramacloud-client-javascript#40]
### Describe the bug

No Orama Cloud import is possible from both jsdelivr and unpkg

Both import from [jsDelivr](https://www.jsdelivr.com/package/npm/@oramacloud/client) and unpkg fail.

```
<script type="module">
import oramacloudclient from 'https://cdn.jsdelivr.net/npm/@oramacloud/client@1.3.14/+esm'
</script>
--> null has no properties
```
```
<script type="module">
import { OramaClient } from 'https://unpkg.com/@oramacloud/client@1.3.14/dist/index.global.js'
</script>
--> doesn't provide an export named: 'OramaClient'
```

Thank you very much.

### To Reproduce

Steps above

### Expected behavior

Import {OramaClient }

### Environment Info

```bash
Firefox + Chrome latest

Oramacloud 1.3.14
```

### Affected areas

Initialization

**Comment by micheleriva** [comment]
Hey @djibe thanks for spotting this!

@faustoq, @matijagaspar, @allevo, can you please look at this?

**Comment by matijagaspar** [comment]
Merged a fix, next release should work, but must import `dist/index.js` because `dist/index.global.js` is not esm but iffe

```
<script type="module">
import { OramaClient } from 'https://unpkg.com/@oramacloud/client@1.3.14/dist/index.js'
</script>
--> doesn't provide an export named: 'OramaClient'
```

**Comment by djibe** [comment]
Works perfectly. Many thanks !
